### PR TITLE
Makes js-lint invoke bundled prettier cli rather than target repo's prettier

### LINKED ISSUE #20: Make js-lint self-contained by invoking the bundled Prettier CLI
### Specification

Projects that don’t list Prettier as a direct dev-dependency fail during the “prettier” phase with spawnSync prettier ENOENT.
This happens because the linter calls prettier by name and the binary is only present in node_modules/.bin when a repo installs Prettier itself or when npm hoists it to the top level.

Making the linter call the bundled Prettier binary guarantees:
- Zero setup – repos only install @matrixai/lint.
- Consistent Prettier version across all projects.
- No accidental breakage when npm’s hoisting rules change.

### Tasks

1. Make the matrixai-lint command invoke the bundled Prettier rather than the target repo's Prettier

### PR DESCRIPTION
**Pull request by CDeltakai**
### Description

This PR replaces the current way js-lint invokes prettier by invoking its local version rather than trying to look for prettier on the target repo's PATH

### Issues Fixed

* Fixes #20 

### Tasks

- [x] 1. Replace the way prettier is currently invoked by making it rely on local dependency first before trying to fallback on the target repo's PATH.

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

File: src/bin/lint.ts [hunk 1]
```diff
@@ -126,38 +127,57 @@ async function main(argv = process.argv) {
...
   try {
-    childProcess.execFileSync('prettier', prettierArgs, {
-      stdio: 'inherit',
-      windowsHide: true,
-      encoding: 'utf-8',
-      shell: platform === 'win32',
-      cwd: process.cwd(),
-    });
+    // Resolves to @matrixai/lint/node_modules/prettier/bin/prettier.cjs
+    prettierBin = require.resolve('prettier/bin/prettier.cjs');
```
Comment (tegefaulkes) [inline src/bin/lint.ts:145]: Don't use `createRequire` this is hack to allow for synchronous dynamic importing of code. If you need to resolve a path to an absolute use `import.meta.url` to get the current directory and use `path.resolve` to resolve that to an absolute path.
